[[custom_groups]]
name = "🌠 节点选择"
rule = [
  "[]🛫 香港专线",
  "[]🏞️ 美利坚高速",
  "[]🌺 日本专线",
  "[]✈️ 手动切换",
  "[]DIRECT",
]
type = "select"

[[custom_groups]]
name = "✈️ 手动切换"
rule = ["[]🏞️ 美利坚高速", "(.*)"]
type = "select"

[[custom_groups]]
name = "🗨️ ChatGPT"
rule = ["[]🏞️ 美利坚高速", "[]🌺 日本专线", "[]✈️ 手动切换"]
type = "select"

[[custom_groups]]
name = "📺 哔哩哔哩"
rule = ["[]DIRECT", "[]🛫 香港专线", "[]✈️ 手动切换"]
type = "select"

[[custom_groups]]
name = "📱 TikTok"
rule = ["[]🌺 日本专线", "[]🏞️ 美利坚高速", "[]✈️ 手动切换"]
type = "select"

[[custom_groups]]
name = "💻 YouTube"
rule = ["[]🌠 节点选择", "[]🛫 香港专线", "[]🏞️ 美利坚高速", "[]✈️ 手动切换"]
type = "select"

[[custom_groups]]
name = "📩 Google"
rule = ["[]🌠 节点选择", "[]🗨️ ChatGPT", "[]🏞️ 美利坚高速", "[]✈️ 手动切换"]
type = "select"

[[custom_groups]]
name = "🏖️ Community"
rule = ["[]🌠 节点选择", "[]🏞️ 美利坚高速", "[]🌺 日本专线", "[]✈️ 手动切换"]
type = "select"

[[custom_groups]]
name = "⛅ OneDrive"
rule = ["[]🪟 Microsoft", "[]🌌 星星啊", "[]DIRECT", "[]🏞️ 美利坚高速", "[]✈️ 手动切换"]
type = "select"

[[custom_groups]]
name = "🎬 Netflix"
rule = ["[]🌺 日本专线", "[]🛫 香港专线", "[]🏞️ 美利坚高速", "[]✈️ 手动切换"]
type = "select"

[[custom_groups]]
name = "🪟 Microsoft"
rule = ["[]🌠 节点选择", "[]🏞️ 美利坚高速", "[]✈️ 手动切换", "[]DIRECT"]
type = "select"

[[custom_groups]]
name = "🛖 国际流媒体"
rule = [
  "[]🌠 节点选择",
  "[]🛫 香港专线",
  "[]🌺 日本专线",
  "[]🏞️ 美利坚高速",
  "[]✈️ 手动切换",
]
type = "select"

[[custom_groups]]
name = "🐳 漏网の鱼"
rule = ["[]🌠 节点选择", "[]🏞️ 美利坚高速", "[]🌺 日本专线", "[]✈️ 手动切换", "[]DIRECT"]
type = "select"

[[custom_groups]]
name = "🌌 星星啊"
rule = ["(下载)", "[]🌠 节点选择", "(.*)"]
type = "select"

[[custom_groups]]
interval = 97
lazy = false
name = "🛫 香港专线"
rule = [
  "[]🎇 香港高速",
  "[]🏞️ 美利坚高速",
]
type = "fallback"
url = "https://www.gstatic.com/generate_204"

[[custom_groups]]
interval = 127
lazy = false
name = "🌺 日本专线"
rule = [
  "[]🗾 日本高速",
  "[]🏞️ 美利坚高速",
]
type = "fallback"
url = "https://www.gstatic.com/generate_204"

[[custom_groups]]
interval = 233
lazy = false
name = "⛳ 美国专线"
rule = [
  "[]🏞️ 美利坚高速",
  "(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|us|United States)",
]
type = "fallback"
url = "https://www.gstatic.com/generate_204"

[[custom_groups]]
name = "🎇 香港高速"
rule = ["(港|HK|hk|Hong Kong|HongKong|hongkong)", "(.*)"]
type = "select"

[[custom_groups]]
name = "🗾 日本高速"
rule = ["!!GROUPID=0!!(^(?=.*(日|东京|大阪|埼玉|JP|jp|Japan))(?!.*尼日利亚).*$)", "(.*)"]
type = "select"

[[custom_groups]]
name = "🏞️ 美利坚高速"
rule = [
  "(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|us|United States)",
  "(.*)",
]
type = "select"
